### ISSUE TITLE
221010-221016

### ISSUE THREAD

**Issue by Jiwon-Yang** [toy-program/issue-driven-algorithm#1]
제목 갠찬나
- 댓글로 문제(3개) 링크 올리기

**Comment by changhoi** [comment]
- https://leetcode.com/problems/the-number-of-weak-characters-in-the-game/
- https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/
- https://school.programmers.co.kr/learn/courses/30/lessons/12920
